#!/usr/bin/env python

import sys
import dbus

bus = dbus.SessionBus()

def jubjub_out(idx):
    obj = bus.get_object('pl.koriakin.Jubjub', '/out{idx}'.format(idx=idx))
    return dbus.Interface(obj, dbus_interface='pl.koriakin.Jubjub.Output')

def jubjub_in(idx):
    obj = bus.get_object('pl.koriakin.Jubjub', '/in{idx}'.format(idx=idx))
    return dbus.Interface(obj, dbus_interface='pl.koriakin.Jubjub.Input')

machines = [ 'ernie', 'dagon', 'cthulhu' ]

cmd = sys.argv[1]

if cmd == 'pulse':
    jubjub_out(sys.argv[2]).Pulse(False)
elif cmd == 'lpulse':
    jubjub_out(sys.argv[2]).Pulse(True)
elif cmd == 'istatus':
    for i in range(8):
        print('{idx}: {state}'.format(idx=i, state=jubjub_in(i).GetState()))
elif cmd == 'status':
    for i, name in enumerate(machines):
        raw = jubjub_in(i).GetState()
        state = 'down' if raw else 'up'
        print('{machine}: {state}'.format(machine=name, state=state))
elif cmd == 'reset':
    name = sys.argv[2]
    idx = machines.index(name)
    jubjub_out(idx*2).Pulse(False)
elif cmd == 'start':
    name = sys.argv[2]
    idx = machines.index(name)
    isdown = jubjub_in(idx).GetState()
    if isdown:
        jubjub_out(idx*2+1).Pulse(False)
elif cmd == 'stop':
    name = sys.argv[2]
    idx = machines.index(name)
    isdown = jubjub_in(idx).GetState()
    if not isdown:
        jubjub_out(idx*2+1).Pulse(False)
elif cmd == 'kill':
    name = sys.argv[2]
    idx = machines.index(name)
    isdown = jubjub_in(idx).GetState()
    if not isdown:
        jubjub_out(idx*2+1).Pulse(True)
else:
    sys.exit('unknown command {cmd}'.format(cmd=cmd))
